### ISSUE TITLE
Add extension.cgroupruntimeextension component

### ISSUE THREAD

**Issue by tttoad** [SigNoz/signoz-otel-collector#586]
Make GC time more stable by using extension.cgroupruntimeextensio .
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/cgroupruntimeextension#cgroup-go-runtime-extension
``` 
extension:
    # processor name: cgroupruntime
    cgroupruntime:
      gomaxprocs:
        enabled: true
      gomemlimit:
        enabled: false
        ratio: 0.8
```
