### ISSUE TITLE
httpcheck_status returns 1 for every http_status_class

### ISSUE THREAD

**Issue by gfelot** [SigNoz/signoz-otel-collector#606]
I want to check a service by pinging a /healthcheck url and get the status.

My Otel conf

```yaml
receivers:
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu: {}
      disk: {}
      load: {}
      filesystem: {}
      memory: {}
      network: {}
      paging: {}
      processes: {}

  # Healthcheck - un receiver par service
  httpcheck/passport:
    collection_interval: 30s
    targets:
      - endpoint: "https://xxx/healthcheck"
        method: GET
        tls:
          insecure_skip_verify: true

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s

  resourcedetection:
    detectors: [env, system]
    timeout: 2s
    system:
      hostname_sources: [os]

  resource/env:
    attributes:
      - key: deployment.environment
        value: "DEV08"
        action: upsert

  # Un processor resource par service healthcheck
  resource/passport:
    attributes:
      - key: service.name
        value: "PASSPORT"
        action: upsert

  transform/http_code:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["health_score"], 3) where attributes["http.status_code"] == 200
          - set(attributes["health_score"], 2) where attributes["http.status_code"] >= 300 and attributes["http.status_code"] < 500
          - set(attributes["health_score"], 1) where attributes["http.status_code"] >= 500

exporters:
#  debug:
#    verbosity: detailed

  clickhousemetricswrite:
    endpoint: tcp://10.24.208.77:9000/signoz_metrics?username=signoz&password=signoz
    tls:
      insecure: true
    resource_to_telemetry_conversion:
      enabled: true

  metadataexporter:
    dsn: tcp://10.24.208.77:9000/signoz_metadata?username=signoz&password=signoz
    timeout: 10s
    tenant_id: default
    cache:
      provider: in_memory

extensions:
  health_check: {}
  zpages: {}

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  extensions: [health_check, zpages]

  pipelines:
    # Un pipeline par service healthcheck
    metrics/passport:
      receivers: [httpcheck/passport]
      processors: [resourcedetection, resource/env, resource/passport, transform/http_code, batch]
      exporters: [clickhousemetricswrite, metadataexporter]

    # Hostmetrics (serveur)
    metrics/hostmetrics:
      receivers: [hostmetrics]
      processors: [resourcedetection, resource/env, batch]
      exporters: [clickhousemetricswrite, metadataexporter]
```

From the official [documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/httpcheckreceiver/README.md)

> This scraper generates a metric with a label for each HTTP response status class with a value of 1 if the status code matches the class.

```
httpcheck.status{http.status_class:1xx, http.status_code:200,...} = 0
httpcheck.status{http.status_class:2xx, http.status_code:200,...} = 1
httpcheck.status{http.status_class:3xx, http.status_code:200,...} = 0
httpcheck.status{http.status_class:4xx, http.status_code:200,...} = 0
httpcheck.status{http.status_class:5xx, http.status_code:200,...} = 0
```

But when I look into the DB I got

```SQL
SELECT *
FROM signoz_metrics.time_series_v4
WHERE metric_name = 'httpcheck_status'
LIMIT 2

Query id: 7d5b1d9a-345c-47b7-b9f3-403a238c8cb8

Row 1:
──────
env:            DEV08
temporality:    Cumulative
metric_name:    httpcheck_status
description:    1 if the check resulted in status_code matching the status_class, otherwise 0.
unit:           1
type:           Sum
is_monotonic:   false
fingerprint:    2673516990800643293
unix_milli:     1749110400000 -- 1.75 trillion
labels:         {"__name__":"httpcheck_status","__temporality__":"Cumulative","deployment_environment":"DEV08","health_score":"3","host_name":"FRPAR3DXDEV08","http_method":"GET","http_status_class":"4xx","http_status_code":"200","http_url":"https://xxx/healthcheck","os_type":"linux","service_name":"PASSPORT"}
attrs:          {}
scope_attrs:    {}
resource_attrs: {}
__normalized:   true

Row 2:
──────
env:            DEV08
temporality:    Cumulative
metric_name:    httpcheck_status
description:    1 if the check resulted in status_code matching the status_class, otherwise 0.
unit:           1
type:           Sum
is_monotonic:   false
fingerprint:    5068959940230499294
unix_milli:     1749110400000 -- 1.75 trillion
labels:         {"__name__":"httpcheck_status","__temporality__":"Cumulative","deployment_environment":"DEV08","health_score":"3","host_name":"FRPAR3DXDEV08","http_method":"GET","http_status_class":"1xx","http_status_code":"200","http_url":"https://xxx/healthcheck","os_type":"linux","service_name":"PASSPORT"}
attrs:          {}
scope_attrs:    {}
resource_attrs: {}
__normalized:   true
```

First answer : ,"http_status_class":"4xx","http_status_code":"200" and -> unit: 1
Second answer : ,"http_status_class":"1xx","http_status_code":"200" and -> unit: 1

I limit the query at 2 but it's the same for all http_status_class, even 2xx.
