### ISSUE TITLE
Persist `service.instance.id` on disk for config reload

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz-otel-collector#63]
The collector's own telemetry resource can be configured as follows.

```
service:
  telemetry:
    resource:
      service.instance.id: xxx
      deployment.environment: xxx
```

Generate one when not provided, write to the config file, and persist the info for config reloads. This should be handled the same as the agent identifier.
